### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
I did a little review :slightly_smiling_face:  That are my change suggestions.

A few additional comments:

I like the CC BY-NC-SA. But for a MagicMirror module, I don't think it's ideal. If an owner runs a small store and has a mirror in the customer area, that's already a commercial use, isn't it? If you don't like a license as permissive as the MIT or ISC, I would suggest the GPL or CC BY-SA 4.0. The decision is yours, of course.

If you choose a license other than MIT, you should change it everywhere. MIT is still mentioned in package.json and MMM-CustomMessage2.js.

GitHub still displays the module as a fork of MMM-Rest. Even if you have used it as a basis, I would detach it from MMM-Rest. In terms of licensing, it is not always easy to change the license of a fork. I would recommend deleting the fork and uploading it as a new independent project: https://stackoverflow.com/a/47974224. But you can also leave it as it is, there are some other modules that still have the same status.

About the name: I somehow don't like version numbers in the name. The current name suggests that it is a continuation of MMM-CustomMessage - but it's not. Maybe you can think of another name. I can't think of anything better either 😅

Making multiple instances possible is a great idea. Couldn't this functionality also be built into MMM-CustomMessage?

### CODE REVIEW

**Comment by dathbe** [comment]
Thanks for the review.

I'm curious why you removed the `\ &&` from the install instructions.  I find it's far easier to copy and past a single command.  And for those who prefer to do it in two steps. they can just leave out the `\ &&` when copying.

Good point on the license.  And I did start from MMM-Rest because I knew I had gotten multiple instances working on that one, but it turns out it's almost entirely re-written, so I'll create a new repo.  

I tried to get multiple instances working on CustomMessage, but had no luck.  It's almost certainly my limited knowledge of javascript, but I couldn't find what the limitation was.  You can post two initial messages, but the update process only ever seems to update the last instance in the config file.  I also have not heard back from the author of that module over a few other comments (which, in fairness, I posted relatively recently).

**Comment by KristjanESPERANTO** [comment]
```sh
cd ~/MagicMirror/modules/MMM-CustomMessage2
git pull
```


```sh
cd ~/MagicMirror/modules/MMM-CustomMessage2 \
&& git pull
```

**Comment by KristjanESPERANTO** [comment]
> And what does global Log mean?

It's relevant for ESLint. Without that ESLint would complain that they are not defined. It's would also be possible to define them in the config file for ESLint.

**Comment by KristjanESPERANTO** [comment]
>  It's almost certainly my limited knowledge of javascript, but I couldn't find what the limitation was.

Building your own module is a good way to learn. So please don't take my question as criticism :slightly_smiling_face:

**Comment by dathbe** [comment]
Neat about being able to copy multiple lines into ssh.
Merged.

**Comment by dathbe** [comment]
Moved here https://github.com/dathbe/MMM-CustomText

**Comment by KristjanESPERANTO** [comment]
Nice! :clap: Add it to the list of modules and if you like, present it in the forum :smiley:

**Pull request merged**
